// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhvHYxO5vS5PVt9TAPNXJ54sH0mwUeV7s',
    appId: '1:388373687527:web:1308fa6036b7e03b16c642',
    messagingSenderId: '388373687527',
    projectId: 'my-culture-trip',
    authDomain: 'my-culture-trip.firebaseapp.com',
    databaseURL: 'https://my-culture-trip-default-rtdb.firebaseio.com',
    storageBucket: 'my-culture-trip.appspot.com',
    measurementId: 'G-L9S9KJMYX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2R2WWD93zse-jRYsaBKzedIEU5U7CUMo',
    appId: '1:388373687527:android:e2e0624fc0845c6916c642',
    messagingSenderId: '388373687527',
    projectId: 'my-culture-trip',
    databaseURL: 'https://my-culture-trip-default-rtdb.firebaseio.com',
    storageBucket: 'my-culture-trip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNN-fqg-3qJjN1-ul3ez9yiAtUGfdhPzk',
    appId: '1:388373687527:ios:3ad03db59442edd916c642',
    messagingSenderId: '388373687527',
    projectId: 'my-culture-trip',
    databaseURL: 'https://my-culture-trip-default-rtdb.firebaseio.com',
    storageBucket: 'my-culture-trip.appspot.com',
    iosClientId: '388373687527-nmg91e5tpgvdr1nf5d1c22ldeoqidkit.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNN-fqg-3qJjN1-ul3ez9yiAtUGfdhPzk',
    appId: '1:388373687527:ios:3ad03db59442edd916c642',
    messagingSenderId: '388373687527',
    projectId: 'my-culture-trip',
    databaseURL: 'https://my-culture-trip-default-rtdb.firebaseio.com',
    storageBucket: 'my-culture-trip.appspot.com',
    iosClientId: '388373687527-nmg91e5tpgvdr1nf5d1c22ldeoqidkit.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureTrip',
  );
}
